import { useState, useEffect, useContext } from 'react';
import { AppContext } from '../context/AppContext';
import { AuthContext } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import api from '../utils/api';
import AddPlotModal from '../components/AddPlotModal';
import DiagnoseModal from '../components/DiagnoseModal';
import IrrigationModal from '../components/IrrigationModal';
import { Sparkles, Calendar, Plus, HeartPulse, Droplets, Sun, LineChart, HelpCircle } from 'lucide-react';

const Dashboard = () => {
    const { language } = useContext(AppContext);
    const { user } = useContext(AuthContext);
    const navigate = useNavigate();
    
    // Translations mapping
    const t = {
        en: { 
            title: "My Farm Plots", 
            addPlot: "+ Add Plot", 
            loading: "Loading your plots...", 
            empty: "You haven't added any plots yet.",
            confirmDelete: "Are you sure you want to delete this plot?",
            failedDelete: "Failed to delete plot",
            welcome: "Welcome,",
            subtitle: "Your AI-powered agricultural assistant is ready to help you optimize farm health. Diagnose plant diseases, schedule smart watering, and inspect crop analytics.",
            coreTools: "Core Farming Tools",
            coreSubtitle: "Everything you need to manage crop health and water efficiency",
            diagTitle: "AI Leaf Diagnosis",
            diagDesc: "Upload photos of sick crop leaves to diagnose diseases, contagiousness risks, and organic remedies.",
            diagBtn: "Diagnose Now →",
            irrigTitle: "Smart Irrigation",
            irrigDesc: "Compute customized watering guidelines based on temperature, rain volume, soil type, and method.",
            irrigBtn: "Get Advice →",
            weatherTitle: "Weather Center",
            weatherDesc: "Monitor live forecasts, wind speed, and humidity indicators for Meerut, Delhi, or custom locations.",
            weatherBtn: "Check Forecast →",
            analyticsTitle: "Crops Analytics",
            analyticsDesc: "Inspect diagnostic histories, check contagion percentages, and review treatment progress metrics.",
            analyticsBtn: "View Timeline →",
            howItWorks: "How it Works",
            howStep1Title: "1. Add Farm Plots 🚜",
            howStep1Desc: "Register your farm plots by specifying the size, location, crop type, and soil information to build your custom field registry.",
            howStep2Title: "2. Run Health Checks 🩺",
            howStep2Desc: "Upload photos of sick crop leaves for immediate AI diagnosis, or check high-precision coordinates-based live weather forecasts.",
            howStep3Title: "3. Take Smart Action 💧",
            howStep3Desc: "Apply organic or chemical remedy plans and run smart water calculators adjusted to regional temperatures and rain levels.",
            dailyTips: "Daily Farming Tips",
            tipsDesc: "Practical daily guidelines to boost your farm's productivity and maintain crop health.",
            tip1Title: "💧 Optimal Watering Timing",
            tip1Desc: "Water your crops in the early morning or late evening. This reduces water evaporation losses and keeps roots hydrated during hot periods.",
            tip2Title: "🌱 Organic Pest Deterrents",
            tip2Desc: "A simple spray of neem oil mixed with warm soapy water is a highly effective, natural defense against aphids and spider mites.",
            tip3Title: "🍃 Airflow & Planting Density",
            tip3Desc: "Avoid dense spacing. Adequate ventilation between plants prevents moisture buildup on leaves, drastically lowering fungal infection risks.",
            disclaimerTitle: "Disclaimer",
            disclaimerText: "Crop Cure is an AI-powered advisory platform designed to assist farmers with predictive crop analysis, general agricultural guidelines, and weather forecasts. The information, diagnostics, and remedies generated by the system are for general educational and planning purposes only. AI diagnoses should not replace professional chemical safety recommendations, local government extension office consultations, or lab-tested soil analysis. Always wear appropriate personal protective gear when handling fertilizers or chemical treatments."
        },
        es: {
            title: "Mis Parcelas de Campo",
            addPlot: "+ Añadir Parcela",
            loading: "Cargando sus parcelas...",
            empty: "Aún no ha añadido ninguna parcela.",
            confirmDelete: "¿Está seguro de que desea eliminar esta parcela?",
            failedDelete: "Error al eliminar la parcela",
            welcome: "¡Bienvenido,",
            subtitle: "Su asistente agrícola impulsado por IA está listo para ayudarle a optimizar la salud del campo. Diagnostique enfermedades, programe el riego y analice cultivos.",
            coreTools: "Herramientas Agrícolas Clave",
            coreSubtitle: "Todo lo que necesita para gestionar la salud del cultivo y la eficiencia del agua",
            diagTitle: "Diagnóstico de Hojas por IA",
            diagDesc: "Suba fotos de hojas enfermas para diagnosticar enfermedades, riesgos de contagio y remedios orgánicos.",
            diagBtn: "Diagnosticar Ahora →",
            irrigTitle: "Riego Inteligente",
            irrigDesc: "Calcule pautas de riego personalizadas basadas en la temperatura, lluvia, tipo de suelo y método.",
            irrigBtn: "Ver Asesoramiento →",
            weatherTitle: "Centro Meteorológico",
            weatherDesc: "Monitoree pronósticos en vivo, velocidad del viento y humedad para Meerut, Delhi o ubicaciones personalizadas.",
            weatherBtn: "Ver Clima →",
            analyticsTitle: "Análisis de Cultivos",
            analyticsDesc: "Inspeccione historiales de diagnóstico, tasas de contagio y métricas de progreso de tratamientos.",
            analyticsBtn: "Ver Historial →",
            howItWorks: "Cómo Funciona",
            howStep1Title: "1. Añadir Parcelas 🚜",
            howStep1Desc: "Registre sus parcelas ingresando su área, ubicación, tipo de cultivo y tipo de suelo.",
            howStep2Title: "2. Diagnosticar el Cultivo 🩺",
            howStep2Desc: "Suba fotos de hojas enfermas para diagnósticos por IA, y revise pronósticos meteorológicos precisos.",
            howStep3Title: "3. Tomar Acción 💧",
            howStep3Desc: "Aplique planes de tratamiento recomendados y calcule pautas inteligentes de irrigación.",
            dailyTips: "Consejos Agrícolas Diarios",
            tipsDesc: "Guías prácticas diarias para mejorar la productividad de su campo y mantener sus cultivos sanos.",
            tip1Title: "💧 Horario de Riego",
            tip1Desc: "Riegue sus cultivos temprano en la mañana o al atardecer para reducir la evaporación del agua.",
            tip2Title: "🌱 Pesticidas Orgánicos",
            tip2Desc: "El aceite de neem diluido en agua tibia es un repelente ecológico muy efectivo contra ácaros y pulgones.",
            tip3Title: "🍃 Espacio y Ventilación",
            tip3Desc: "Evite la siembra muy densa. La buena circulación de aire previene la proliferación de hongos.",
            disclaimerTitle: "Descargo de Responsabilidad",
            disclaimerText: "Crop Cure es una plataforma asesora impulsada por IA diseñada para ayudar a los agricultores con análisis predictivos y pautas generales. Los resultados generados son solo para fines informativos y educativos. Los diagnósticos de IA no reemplazan la asesoría de ingenieros agrónomos, los análisis de suelo de laboratorio ni las regulaciones locales sobre pesticidas."
        },
        hi: { 
            title: "मेरे खेत के प्लॉट", 
            addPlot: "+ प्लॉट जोड़ें", 
            loading: "आपके प्लॉट लोड हो रहे हैं...", 
            empty: "आपने अभी तक कोई प्लॉट नहीं जोड़ा है।",
            confirmDelete: "क्या आप वाकई इस प्लॉट को हटाना चाहते हैं?",
            failedDelete: "प्लॉट हटाने में विफल",
            welcome: "स्वागत है,",
            subtitle: "आपका एआई-संचालित कृषि सहायक आपकी खेत की सेहत को बेहतर बनाने के लिए तैयार है। फसलों के रोगों का निदान करें, स्मार्ट सिंचाई शेड्यूल करें और विश्लेषण देखें।",
            coreTools: "मुख्य कृषि उपकरण",
            coreSubtitle: "फसल स्वास्थ्य और जल दक्षता का प्रबंधन करने के लिए आपकी जरूरत की हर चीज",
            diagTitle: "एआई पत्ती निदान",
            diagDesc: "रोगों, संक्रामक खतरों और जैविक उपचारों का निदान करने के लिए बीमार पत्ती की तस्वीरें अपलोड करें।",
            diagBtn: "अभी निदान करें →",
            irrigTitle: "स्मार्ट सिंचाई",
            irrigDesc: "तापमान, वर्षा, मिट्टी के प्रकार और सिंचाई विधि के आधार पर कस्टम सिंचाई दिशानिर्देश प्राप्त करें।",
            irrigBtn: "सिंचाई सलाह →",
            weatherTitle: "मौसम केंद्र",
            weatherDesc: "मेरठ, दिल्ली या किसी भी शहर के लिए लाइव पूर्वानुमान, हवा की गति और आर्द्रता के संकेतकों की निगरानी करें।",
            weatherBtn: "मौसम देखें →",
            analyticsTitle: "फसल विश्लेषण",
            analyticsDesc: "पिछले पत्ती रोगों के इतिहास, संक्रामक दर और उपचार प्रगति के आंकड़ों की समीक्षा करें।",
            analyticsBtn: "टाइमलाइन देखें →",
            howItWorks: "यह कैसे काम करता है",
            howStep1Title: "1. खेत के प्लॉट जोड़ें 🚜",
            howStep1Desc: "अपने खेतों का आकार, स्थान, फसल का प्रकार और मिट्टी की जानकारी दर्ज करके उन्हें पंजीकृत करें।",
            howStep2Title: "2. स्वास्थ्य जांच चलाएं 🩺",
            howStep2Desc: "तुरंत एआई निदान के लिए बीमार पत्तियों की तस्वीरें अपलोड करें और लाइव मौसम का पूर्वानुमान देखें।",
            howStep3Title: "3. स्मार्ट सिंचाई करें 💧",
            howStep3Desc: "तापमान और वर्षा के अनुसार समायोजित सिंचाई सलाह लें और अनुशंसित जैविक उपचार योजनाएं लागू करें।",
            dailyTips: "दैनिक कृषि सुझाव",
            tipsDesc: "खेत की उत्पादकता बढ़ाने और फसलों को स्वस्थ रखने के लिए व्यावहारिक दैनिक सुझाव।",
            tip1Title: "💧 पानी देने का सही समय",
            tip1Desc: "फसलों को सुबह जल्दी या शाम को पानी दें। इससे पानी का वाष्गीकरण कम होता है और जड़ें नम रहती हैं।",
            tip2Title: "🌱 जैविक कीट नियंत्रण",
            tip2Desc: "नीम के तेल और गुनगुने पानी का मिश्रण एफिड्स और स्पाइडर माइट्स के खिलाफ एक प्रभावी प्राकृतिक सुरक्षा है।",
            tip3Title: "🍃 वेंटिलेशन और दूरी",
            tip3Desc: "फसलों के बीच पर्याप्त दूरी रखें। हवा का प्रवाह पत्तियों पर नमी जमा होने से रोकता है, जिससे कवक (फंगस) का खतरा कम होता है।",
            disclaimerTitle: "अस्वीकरण",
            disclaimerText: "क्रॉप क्योर (Crop Cure) एक एआई-संचालित सलाहकार मंच है जो किसानों को पूर्वानुमानित फसल विश्लेषण, कृषि दिशानिर्देश और मौसम के पूर्वानुमान में मदद करने के लिए बनाया गया है। एआई निदान केवल सामान्य मार्गदर्शन के लिए हैं। किसी भी रासायनिक उपचार या खाद के उपयोग से पहले कृषि विशेषज्ञों या मृदा परीक्षण लैब से सलाह अवश्य लें।"
        }
    };
    const lang = t[language] || t.en;

    const [plots, setPlots] = useState([]);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [loading, setLoading] = useState(true);
    const [selectedPlotForDiagnosis, setSelectedPlotForDiagnosis] = useState(null);
    const [selectedPlotForIrrigation, setSelectedPlotForIrrigation] = useState(null);

    useEffect(() => {
        const fetchPlots = async () => {
            try {
                const response = await api.get('/plots');
                setPlots(response.data);
            } catch (error) {
                console.error('Error fetching plots:', error);
            } finally {
                setLoading(false);
            }
        };
        fetchPlots();
    }, []);

    const handlePlotAdded = (newPlot) => {
        setPlots([newPlot, ...plots]);
    };

    return (
        <div className="w-full text-left animate-slide-up">
            {/* Hero / Welcome section */}
            <div className="relative p-8 mb-10 text-white rounded-3xl bg-gradient-to-br from-emerald-600 via-emerald-700 to-teal-800 overflow-hidden flex flex-col md:flex-row items-center justify-between gap-8 shadow-lg shadow-emerald-700/10">
                <div className="absolute inset-0 bg-grid-pattern opacity-10 pointer-events-none"></div>
                <div className="z-10 text-left max-w-2xl">
                    <div className="flex items-center gap-2 px-3 py-1 bg-white/10 backdrop-blur-md rounded-full text-xs font-bold w-fit mb-4">
                        <Sparkles size={12} className="text-emerald-350" />
                        <span>Agricultural Intelligence Active</span>
                    </div>
                    <h1 className="text-3xl sm:text-4xl font-extrabold text-white mb-3 tracking-tight">
                        {lang.welcome} {user?.username || 'Farmer'}! 🌾👋
                    </h1>
                    <p className="text-sm sm:text-base font-medium text-emerald-100/90 leading-relaxed mb-8">
                        {lang.subtitle}
                    </p>
                    <div className="flex flex-wrap gap-3">
                        <button
                            disabled={loading}
                            onClick={() => {
                                if (plots.length > 0) {
                                    setSelectedPlotForDiagnosis(plots[0]);
                                } else {
                                    setIsModalOpen(true);
                                }
                            }}
                            className="px-5 py-3 bg-white hover:bg-emerald-50 text-emerald-700 disabled:bg-gray-100 disabled:text-gray-400 font-extrabold rounded-xl shadow-md border-none cursor-pointer transition-all active:scale-[0.98] text-sm"
                        >
                            Diagnose Leaf 🩺
                        </button>
                        <button
                            onClick={() => setIsModalOpen(true)}
                            className="px-5 py-3 bg-transparent text-white border border-white/40 font-extrabold rounded-xl cursor-pointer hover:bg-white/10 transition-all active:scale-[0.98] text-sm"
                        >
                            {lang.addPlot} 🚜
                        </button>
                    </div>
                </div>
                <div className="hidden md:flex flex-col items-center gap-1.5 z-10 select-none bg-white/5 backdrop-blur-sm p-6 rounded-2xl border border-white/10 shrink-0">
                    <span className="text-7xl filter drop-shadow-md">🚜</span>
                    <span className="text-[10px] uppercase tracking-widest font-black text-emerald-250">CropCure OS</span>
                </div>
                <div className="absolute right-[-40px] top-[-40px] w-64 h-64 bg-white/5 rounded-full blur-2xl pointer-events-none"></div>
            </div>

            {/* Core Farming Tools Section */}
            <div className="mb-14 text-left">
                <div className="mb-6">
                    <h2 className="text-2xl font-black text-slate-850 dark:text-slate-100 tracking-tight">{lang.coreTools}</h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">{lang.coreSubtitle}</p>
                </div>
                
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                    {/* Diagnose Tool (Green) */}
                    <div className="flex flex-col justify-between p-6 bg-white dark:bg-gray-900 border border-slate-200/50 dark:border-gray-800/50 hover:border-emerald-400 dark:hover:border-emerald-700 rounded-2xl shadow-sm hover:shadow-md hover:shadow-emerald-500/5 hover:-translate-y-0.5 transition-all duration-300 group">
                        <div className="text-left">
                            <div className="w-12 h-12 bg-emerald-50 dark:bg-emerald-950/20 text-2xl rounded-xl flex items-center justify-center group-hover:scale-105 transition-transform">
                                🩺
                            </div>
                            <h3 className="text-base font-extrabold text-slate-800 dark:text-slate-200 mt-4">{lang.diagTitle}</h3>
                            <p className="text-xs text-gray-500 dark:text-gray-400 mt-2 leading-relaxed font-medium">{lang.diagDesc}</p>
                        </div>
                        <button 
                            disabled={loading}
                            onClick={() => {
                                if (plots.length > 0) {
                                    setSelectedPlotForDiagnosis(plots[0]);
                                } else {
                                    setIsModalOpen(true);
                                }
                            }}
                            className="w-full mt-6 py-2.5 px-4 bg-emerald-500 hover:bg-emerald-600 disabled:bg-gray-200 text-white font-extrabold rounded-xl text-xs border-none cursor-pointer shadow-sm active:scale-[0.98] transition-all"
                        >
                            {loading ? "Loading..." : lang.diagBtn}
                        </button>
                    </div>

                    {/* Irrigation Advice Tool (Blue) */}
                    <div className="flex flex-col justify-between p-6 bg-white dark:bg-gray-900 border border-slate-200/50 dark:border-gray-800/50 hover:border-blue-400 dark:hover:border-blue-700 rounded-2xl shadow-sm hover:shadow-md hover:shadow-blue-500/5 hover:-translate-y-0.5 transition-all duration-300 group">
                        <div className="text-left">
                            <div className="w-12 h-12 bg-blue-50 dark:bg-blue-950/20 text-2xl rounded-xl flex items-center justify-center group-hover:scale-105 transition-transform">
                                💧
                            </div>
                            <h3 className="text-base font-extrabold text-slate-800 dark:text-slate-200 mt-4">{lang.irrigTitle}</h3>
                            <p className="text-xs text-gray-500 dark:text-gray-400 mt-2 leading-relaxed font-medium">{lang.irrigDesc}</p>
                        </div>
                        <button 
                            disabled={loading}
                            onClick={() => {
                                if (plots.length > 0) {
                                    setSelectedPlotForIrrigation(plots[0]);
                                } else {
                                    setIsModalOpen(true);
                                }
                            }}
                            className="w-full mt-6 py-2.5 px-4 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-200 text-white font-extrabold rounded-xl text-xs border-none cursor-pointer shadow-sm active:scale-[0.98] transition-all"
                        >
                            {loading ? "Loading..." : lang.irrigBtn}
                        </button>
                    </div>

                    {/* Weather Tool (Teal) */}
                    <div className="flex flex-col justify-between p-6 bg-white dark:bg-gray-900 border border-slate-200/50 dark:border-gray-800/50 hover:border-cyan-400 dark:hover:border-cyan-700 rounded-2xl shadow-sm hover:shadow-md hover:shadow-cyan-500/5 hover:-translate-y-0.5 transition-all duration-300 group">
                        <div className="text-left">
                            <div className="w-12 h-12 bg-cyan-50 dark:bg-cyan-950/20 text-2xl rounded-xl flex items-center justify-center group-hover:scale-105 transition-transform">
                                🌦️
                            </div>
                            <h3 className="text-base font-extrabold text-slate-800 dark:text-slate-200 mt-4">{lang.weatherTitle}</h3>
                            <p className="text-xs text-gray-505 dark:text-gray-400 mt-2 leading-relaxed font-medium">{lang.weatherDesc}</p>
                        </div>
                        <button 
                            onClick={() => navigate('/weather')}
                            className="w-full mt-6 py-2.5 px-4 bg-cyan-600 hover:bg-cyan-700 text-white font-extrabold rounded-xl text-xs border-none cursor-pointer shadow-sm active:scale-[0.98] transition-all"
                        >
                            {lang.weatherBtn}
                        </button>
                    </div>

                    {/* Analytics Timeline Tool (Purple) */}
                    <div className="flex flex-col justify-between p-6 bg-white dark:bg-gray-900 border border-slate-200/50 dark:border-gray-800/50 hover:border-purple-400 dark:hover:border-purple-700 rounded-2xl shadow-sm hover:shadow-md hover:shadow-purple-500/5 hover:-translate-y-0.5 transition-all duration-300 group">
                        <div className="text-left">
                            <div className="w-12 h-12 bg-purple-50 dark:bg-purple-950/20 text-2xl rounded-xl flex items-center justify-center group-hover:scale-105 transition-transform">
                                📊
                            </div>
                            <h3 className="text-base font-extrabold text-slate-800 dark:text-slate-200 mt-4">{lang.analyticsTitle}</h3>
                            <p className="text-xs text-gray-500 dark:text-gray-400 mt-2 leading-relaxed font-medium">{lang.analyticsDesc}</p>
                        </div>
                        <button 
                            onClick={() => navigate('/crops')}
                            className="w-full mt-6 py-2.5 px-4 bg-purple-600 hover:bg-purple-700 text-white font-extrabold rounded-xl text-xs border-none cursor-pointer shadow-sm active:scale-[0.98] transition-all"
                        >
                            {lang.analyticsBtn}
                        </button>
                    </div>
                </div>
            </div>

            {/* How It Works Section */}
            <div className="mt-14 text-left">
                <div className="mb-6">
                    <h2 className="text-2xl font-black text-slate-850 dark:text-white tracking-tight flex items-center gap-2">
                        🛠️ {lang.howItWorks}
                    </h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                        Follow these simple steps to analyze crop health and save water
                    </p>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="p-6 bg-white dark:bg-gray-900 border border-l-4 border-l-emerald-500 border-slate-200/50 dark:border-gray-800/50 rounded-r-2xl rounded-l-md shadow-sm">
                        <h4 className="font-extrabold text-slate-800 dark:text-slate-100 text-sm">
                            {lang.howStep1Title}
                        </h4>
                        <p className="text-xs text-slate-500 dark:text-slate-400 mt-2.5 leading-relaxed font-medium">
                            {lang.howStep1Desc}
                        </p>
                    </div>
                    <div className="p-6 bg-white dark:bg-gray-900 border border-l-4 border-l-blue-500 border-slate-200/50 dark:border-gray-800/50 rounded-r-2xl rounded-l-md shadow-sm">
                        <h4 className="font-extrabold text-slate-800 dark:text-slate-100 text-sm">
                            {lang.howStep2Title}
                        </h4>
                        <p className="text-xs text-slate-500 dark:text-slate-400 mt-2.5 leading-relaxed font-medium">
                            {lang.howStep2Desc}
                        </p>
                    </div>
                    <div className="p-6 bg-white dark:bg-gray-900 border border-l-4 border-l-teal-500 border-slate-200/50 dark:border-gray-800/50 rounded-r-2xl rounded-l-md shadow-sm">
                        <h4 className="font-extrabold text-slate-800 dark:text-slate-100 text-sm">
                            {lang.howStep3Title}
                        </h4>
                        <p className="text-xs text-slate-500 dark:text-slate-400 mt-2.5 leading-relaxed font-medium">
                            {lang.howStep3Desc}
                        </p>
                    </div>
                </div>
            </div>

            {/* Daily Tips Section */}
            <div className="mt-14 text-left">
                <div className="mb-6">
                    <h2 className="text-2xl font-black text-slate-850 dark:text-white tracking-tight flex items-center gap-2">
                        💡 {lang.dailyTips}
                    </h2>
                    <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                        {lang.tipsDesc}
                    </p>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="p-6 bg-white dark:bg-gray-900 border border-slate-200/50 dark:border-gray-800/50 rounded-2xl shadow-sm hover:shadow-md transition-all">
                        <h4 className="font-extrabold text-slate-800 dark:text-slate-200 text-base flex items-center gap-2">
                            {lang.tip1Title}
                        </h4>
                        <p className="text-xs text-slate-505 dark:text-gray-400 leading-relaxed mt-3 font-medium">
                            {lang.tip1Desc}
                        </p>
                    </div>
                    <div className="p-6 bg-white dark:bg-gray-900 border border-slate-200/50 dark:border-gray-800/50 rounded-2xl shadow-sm hover:shadow-md transition-all">
                        <h4 className="font-extrabold text-slate-800 dark:text-slate-200 text-base flex items-center gap-2">
                            {lang.tip2Title}
                        </h4>
                        <p className="text-xs text-slate-505 dark:text-gray-400 leading-relaxed mt-3 font-medium">
                            {lang.tip2Desc}
                        </p>
                    </div>
                    <div className="p-6 bg-white dark:bg-gray-900 border border-slate-200/50 dark:border-gray-800/50 rounded-2xl shadow-sm hover:shadow-md transition-all">
                        <h4 className="font-extrabold text-slate-800 dark:text-slate-200 text-base flex items-center gap-2">
                            {lang.tip3Title}
                        </h4>
                        <p className="text-xs text-slate-505 dark:text-gray-400 leading-relaxed mt-3 font-medium">
                            {lang.tip3Desc}
                        </p>
                    </div>
                </div>
            </div>

            {/* Disclaimer Panel */}
            <div className="mt-16 mb-6 p-6 border border-red-200/60 dark:border-red-950/40 bg-red-50/20 dark:bg-red-950/10 rounded-2xl text-left">
                <h4 className="text-sm font-extrabold text-red-700 dark:text-red-400 flex items-center gap-1.5 uppercase tracking-wider">
                    ⚠️ {lang.disclaimerTitle}
                </h4>
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-2.5 leading-relaxed font-medium">
                    {lang.disclaimerText}
                </p>
            </div>

            <AddPlotModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} onPlotAdded={handlePlotAdded} />
            <DiagnoseModal isOpen={!!selectedPlotForDiagnosis} onClose={() => setSelectedPlotForDiagnosis(null)} plot={selectedPlotForDiagnosis} />
            <IrrigationModal isOpen={!!selectedPlotForIrrigation} onClose={() => setSelectedPlotForIrrigation(null)} plot={selectedPlotForIrrigation} />
        </div>
    );
};

export default Dashboard;